- name: Clean 
  hosts: db
  remote_user: root  

  vars_files:
    - conf/env_vars.yaml
    - conf/env_db.yaml

  tasks:
    - include: play/cleanun.yaml
    
    - name: 'Remove {{ imagefile }}'
      file:
        path: '/tmp/{{ imagefile }}'
        state: absent

    - include: play/uninstallprev.yaml


