- name: Upgrade DB2
  hosts: db
  remote_user: root  

  vars_files:
    - conf/env_vars.yaml
    - conf/env_db.yaml

  tasks:
    - include: play/db2stop.yaml
      become_user: db2inst1
      become: true
      become_method: su
      become_flags: "-"
#      when: False

    - include: play/cleanun.yaml
#      when: False

    - include: play/copyfp.yaml
#      when: False

    - include: play/upgradedb2.yaml
#      when: False
  
    - include: play/updatedb.yaml
      become_user: db2inst1
      become: true
      become_method: su
      become_flags: "-"
#      debugger: always
#      when: False

#    - debug: var=out.stdout_lines

